global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  insecure: true

log:
  level: DEBUG

accessLog: {}


providers:
  docker:
    watch: true
    exposedbydefault: false

entryPoints:
  http:
    address: ":80"
